export const CAL_EVENT_LIST = "CAL_EVENT_LIST";
export const CAL_EVENT_LIST_COMPLETE = "CAL_EVENT_LIST_COMPLETE";
export const CAL_EVENT_ADD = "CAL_EVENT_ADD";
export const CAL_EVENT_UPDATE = "CAL_EVENT_UPDATE";

export const TODO_EVENT_LIST = "TODO_EVENT_LIST";
export const TODO_EVENT_LIST_COMPLETE = "TODO_EVENT_LIST_COMPLETE";
export const TODO_EVENT_ADD = "TODO_EVENT_ADD";
export const TODO_EVENT_UPDATE = "TODO_EVENT_UPDATE";

export const LAYOUT_EVENT_LIST = "LAYOUT_EVENT_LIST";
export const LAYOUT_EVENT_LIST_COMPLETE = "LAYOUT_EVENT_LIST_COMPLETE";
export const LAYOUT_EVENT_ADD = "LAYOUT_EVENT_ADD";
export const LAYOUT_EVENT_UPDATE = "LAYOUT_EVENT_UPDATE";
