export const CAL_EVENT_LIST = "CAL_EVENT_LIST";
export const CAL_EVENT_LIST_COMPLETE = "CAL_EVENT_LIST_COMPLETE";
export const CAL_EVENT_ADD = "CAL_EVENT_ADD";
export const CAL_EVENT_UPDATE = "CAL_EVENT_UPDATE";